### ISSUE TITLE
Issue with lastdb

### ISSUE THREAD

**Issue by gp79** [adamewing/tebreak#13]
Hi Adam,
I am trying to run Tebreak on some test L1/Alu capture libraries (150bp PE aligned with BWA mem -Y -M) and I am getting this warning message right at the start after the reference genome is loaded in memory:

**Warning: could not lastdb -4G /tmp/tebreak.concat.fa.0054f6df-b393-4ca0-81aa-40b16fcff0a6.fa /tmp/tebreak.concat.fa.0054f6df-b393-4ca0-81aa-40b16fcff0a6.fa
Warning: no lastdb index for /tmp/tebreak.concat.fa.0054f6df-b393-4ca0-81aa-40b16fcff0a6.fa**

,repeat N times.
What could be the possible reason and fix?
My lastdb version is running smooth otherwise if tested outside Tebreak.

Thank you in advance.

**Comment by adamewing** [comment]
Hi,

This is usually because of the specific LAST version, if you're using the latest, try replacing it with version 716 (http://last.cbrc.jp/last-716.zip).

**Comment by gp79** [comment]
Thanks for your fast reply!
This error was generated by version 716 so it must be something else...both versions 941 (latest) and 716 give the same problem.

I have just discovered that it may be a permission problem on our side: if I run tebreak on a local node it runs smoothly, but the warnings show up if I submit the job to our GRID system.
In this last case, when tebreak calls minia and last to improve the consensus breakends then something goes wrong (the x.concat.fa files are all empty and no tebreak.minia.x files are generated).

**Comment by gp79** [comment]
Solved! 
Just in case anybody else should have this issue, it was resolved by modifying the tebreak.py file to add the full path to minia in the following line:

cmd = ['minia', '-in', fq, '-abundance-min', param, '-no-length-cutoff', '-nb-cores', '1', '-out', ctgbase]

So in my case:

cmd = ['/home/gp79/bin/minia', '-in', fq, '-abundance-min', param, '-no-length-cutoff', '-nb-cores', '1', '-out', ctgbase]

Cheers.

**Comment by adamewing** [comment]
Ah, good. Alternatively, just make sure the minia binary is in your $PATH

**Comment by gp79** [comment]
That was the tricky, minia was correctly installed in my $PATH but for some weird reason the python script could not see it unless specified as above.
Thank you and have a great day!
