### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vasilislenis** [adamewing/tebreak#14]
Hello Adam,

I am really sorry for bothering you but unfortunately, I have an installation problem. I have followed all the installation steps that you describe without any issue but when I'm trying to test the tebreak command I'm getting the following:
```
    encountered error in chunk: 4:50000000-60000000:0-10000000
    Traceback (most recent call last):
    File "./tebreak.py", line 1972, in run_chunk
    processed_insertions  = postprocess_insertions(insertions, filters, args.bwaref, bams,     tmpdir=args.tmpdir, rescue_asm=args.rescue_asm)
    File "./tebreak.py", line 1786, in postprocess_insertions
    ins.improve_consensus(support_asm, bwaref, tmpdir=tmpdir)
   File "./tebreak.py", line 699, in improve_consensus
    build_last_db(ctg_fa)
   File "./tebreak.py", line 1417, in build_last_db
    subprocess.call(['lastdb', '-s', '4G', fa, fa])
   File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
    File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
   OSError: [Errno 2] No such file or directory
```

I am trying to install it locally on a cluster without having a sudo access but apart from this error, I didn't found any other problem on the dependencies.

Thank you very much in advance,
Vasilis.

**Comment by adamewing** [comment]
Hi Vasilis,

It's no bother - could you verify that you have a working lastdb installation and that it's in the $PATH where you're running tebreak.py?

**Comment by vasilislenis** [comment]
Hi Adam, 

Thank you very much for your help!

It looks like that I haven’t put the last binaries on the $PATH, which I fixed it!

Now, I have another issue with align. It cannot identify the module.

The problem is that I don’t have a sudo access, so I am trying to install it locally.

All the python modules that I have installed with pip are installed on this directory:

/home/x.v.l.01/.local/lib/python2.7/site-packages

But unfortunately the align is installed (accidentally) in this directory:

/home/x.v.l.01/lib64/python2.7/site-packages

Which includes (align-0.1-py2.7-linux-x86_64.egg, easy-install.pth, site.py, site.pyc)

I really don’t know if it is installed appropriately even in the wrong directory.

The problem is that when I am giving the installation command like this:

python setup.py install --prefix=/home/x.v.l.01/.local/lib/python2.7/site-packages/

Or

python setup.py install --prefix=/home/x.v.l.01/.local

It gives me the following error:

TEST FAILED: /home/x.v.l.01/.local/lib64/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

My apologies again for annoying you, but I believe that I am so close….

Many many thanks,
Vasilis.

**Comment by vasilislenis** [comment]
Hi Adam, 

I hope my email finds you well.

Terribly sorry for bothering you again but I have a small issue with resolve.py.

I manage to install tiebreak locally (many thanks for your help!!) and the first set it goes really smoothly…

The problem is when I am trying to run the resolve step I am getting an error of a missing file ( attaching the error at the end of the email) but it also generates the output files .resolve.out and table.txt, although, the table.out seems to be empty (it has a header).

Is it possible to have faced this trouble before?

Thank you very much for help in advance,
Vasilis.

RESOLVE STEP ERROR:


Traceback (most recent call last):
  File "/home/x.v.l.01/tebreak/tebreak/resolve.py", line 1110, in resolve_insertion
    tmp_bam = remap_discordant(ins, inslib_fa=inslib_fa, tmpdir=args.refoutdir)
  File "/home/x.v.l.01/tebreak/tebreak/resolve.py", line 961, in remap_discordant
    tmp_ref = make_tmp_ref(ins, inslib_fa, tmpdir)
  File "/home/x.v.l.01/tebreak/tebreak/resolve.py", line 951, in make_tmp_ref
    return prepare_ref(tmp_ref, refoutdir=tmpdir, makeLAST=False)
  File "/home/x.v.l.01/tebreak/tebreak/resolve.py", line 631, in prepare_ref
    subprocess.call(['samtools', 'faidx', ref_fa])
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Insertion location: hs37d5:35079875

**Comment by vasilislenis** [comment]
Hi Adam, 

Please, ignore my last email. I believe that I have fixed it!

I had a small issue with the paths (samtools, bcftools and exonerate should be included in the home  path).

Many thanks,
Vasilis.
