### ISSUE TITLE
Running TEBreak on cluster issue

### ISSUE THREAD

**Issue by vasilislenis** [adamewing/tebreak#15]
Hi Adam,

I am afraid that I have a problem with running TEBreak.
After the installation, I have tried to run it with an alignment file (~50GB bam) and it ran smoothly on my cluster (Slurm based).
Now, I am facing the following situation:
I am trying to run it on a larger file (~100GB) and for no specific reason it isn't crashing or signaling an error state. It's just exiting (I don't have any error in the log files. No crashing indications, no memory errors).

It generates the chunklist but the .tebreak.disc.txt and the  .pickle output are empty.
I have checked the detail.out and there is only the command that I have used.
Also, there is no tebreak_refs/ directory.

Any idea about what it can be wrong?

Here is the command that I am submitting:

`python ~/path_to_TEBreak/tebreak/tebreak.py -b path_to_bam/XXXX.bam -r path_to_ref/REF/HumanNCBI37_UCSC_XX.fa -p 40 -d ~/path_to_TEBreak/tebreak/lib/hg19.te.disctgt.txt -m ~/path_to_TEBreak/tebreak/lib/hg38.centromere_telomere.bed --max_ins_reads 1000 --debug --pickle path_to_TE_OUT/TE_pFile.pickle  --detail_out path_to_TE_OUT/detailedFile.detail.out`

**Comment by adamewing** [comment]
Hi,

Your command line arguments are a mixture of hg19 and hg38. All of the files you use have to correspond to the same reference genome, including the reference, the BAM file, and any annotation files. Also be careful to either use or don't use the 'chr' prefix for chromosome names consistently across all inputs. Hope that solves it, let me know.

--Adam

**Comment by vasilislenis** [comment]
Hi Adam,

Thank you very much for your reply.
Yes, apparently, there were two issues. The mixture of the reference version and the chromosomes’ names. In my reference, the "chr" prefix was there, so I had to include it in the annotation files as well.

Now it works fine.

Many thanks,
Vasilis.

**Comment by adamewing** [comment]
Great!
