### ISSUE TITLE
somatic L1 insertions

### ISSUE THREAD

**Issue by MinS1** [adamewing/tebreak#16]
Hi, adam,

I have obtained the result tables of L1 insertions of tumor and normal tissue of multisamples, but how can I get the somatic L1 insertions from these results tables?  Just comparing the two tables, which appear in tumor and do not appear in normal?

Best.
Shishi

**Comment by adamewing** [comment]
Hi Shishi, The best way to go about this is to feed tebreak.py with both the tumour and normal .bam files in the same run. The `-b` parameter takes multiple .bam files either as a comma-delimited list or as a .txt file containing paths to .bam files. Let me know if this makes sense. Then, in the output (i.e. once you've run `resolve.py` on the .pickle file generated by `tebreak.py`) you'll be looking for calls with support only from the tumour sample. I would also recommend eliminating any known non-reference insertions from the list of putative somatic insertion calls.

--Adam

**Comment by MinS1** [comment]
Hi, Adam,

Thank you!
When I set the -b parameter with two .bam files(1tumor and 1matched normal), the running of tebreak.py was success. I have obtained the corresponding .pickle file.
When I  set the -b parameter with multiple .bam files(8 tumor and 8 normal) either as a comma-delimited list, the tebreak.py process has been running for almost half a month without result. It was killed this morning with unknown reason.  How can I solve this problem?

Best,
Shishi

**Comment by adamewing** [comment]
I wouldn't recommend feeding tebreak more than 2-3 WGS bam files at once or you'll end up waiting too long. What I would recommend in your case is running each tumour + normal pair individually, then using the merged intervals from the outputs across all pairs as input for a final tebreak run across all samples but just on the merged intervals.

In other words, take columns 2,3, and 4 of *.table.txt file output from `resolve.py` for each tumour normal pair, concatenate them all into a big list, sort them (i.e. `sort -k1,1 -k2,2n`), and use `bedtools merge` to merge overlapping intervals. Then feed that interval file to tebreak using the parameter `-i` and run across all 16 .bam files at once, then run `resolve.py` on the final .pickle output and you should get a set of joint insertion calls for your cohort. Let me know if you need more detail, good luck!
