### ISSUE TITLE
Issue with test data

### ISSUE THREAD

**Issue by varshini712** [adamewing/tebreak#7]
Hi Adam,

I was trying to use your test data to check if all the packages and tools are installed properly. However, I keep getting the following error:
**"encountered error in chunk 4:57459002:57496002
Traceback (most recent call last):
  File "tebreak/tebreak.py", line 1807, in run_chunk
    sr = fetch_clipped_reads(bams, chrom, start, end, filters, logger=logger)
  File "tebreak/tebreak.py", line 1132, in fetch_clipped_reads
    for read in bam.fetch(chrom, start, end):
  File "pysam/libcalignmentfile.pyx", line 825, in pysam.libcalignmentfile.AlignmentFile.fetch (pysam/libcalignmentfile.c:10791)
  File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.parse_region (pysam/libcalignmentfile.c:10251)
ValueError: invalid reference `4`"**

I checked both the test bam file and the fasta file you have provided in your GitHub page. I don't understand why this error occurs. If you can help me with this it would be really great!

Thanks!

**Comment by adamewing** [comment]
Try using: `test/data/Homo_sapiens_chr4_50000000-60000000_assembly19.fasta` as the reference genome. The TEBreak test uses this small chunk as the reference to save space in the repository, so you'll need to run against that to get it working. If I'm guessing at the problem wrong, let me know what the full command line argument was.

**Comment by varshini712** [comment]
I used exactly how it was mentioned in your documentation:
**tebreak/tebreak.py -b test/data/example.ins.bam -r test/data/Homo_sapiens_chr4_50000000-60000000_assembly19.fasta -i test/data/example.region.bed --pickle test/example.pickle --detail_out test/example.tebreak.detail.out**

**Comment by varshini712** [comment]
Hi Adam,

I am able to run the test script without the bed region. If I provide the interval-bed as given in your test data, it throws an error!

**Comment by MischaLundberg** [comment]
@varshini712 this is an issue in the Manual. We will fix it. 
Test it without the -i option.
E.g.:
tebreak/tebreak.py -b test/data/example.ins.bam -r test/data/Homo_sapiens_chr4_50000000-60000000_assembly19.fasta --pickle test/example.pickle --detail_out test/example.tebreak.detail.out

The Error occurs because of the name used in the .fasta file (>4:50000000-60000000), which is not the the same as in the bed file (4	57459002	57496002).

**Comment by adamewing** [comment]
Fixed #8 sorry for the confusion.

--Adam

**Comment by varshini712** [comment]
Thanks a lot for your help! It works now!
