### ISSUE TITLE
Sometimes the headers don't match the data

### ISSUE THREAD

**Issue by Martingales** [adamewing/tebreak#9]
Hi,

in around a quarter of my runs I detect discrepancies in the output table. The header of the output table sometimes omit the "Sample_support_3p" name but still supplying the data. Hence the header is one column short compared to the data. In other cases, the columns "Sample_support_5p" and "Sample_support_3p" are switched in order.
[github_example.txt](https://github.com/adamewing/tebreak/files/1507014/github_example.txt)

Am I the only one with this problem? Or have I forgot a command-line option when calling tebreak?

**Comment by adamewing** [comment]
Hi,

This _should_ have been fixed as of a few commits ago (https://github.com/adamewing/tebreak/commit/651cfc2d14c1471455effa24bf74289e04fabe72) - can you let me know if you've updated your tebreak version recently (e.g. via `git pull`)?

Please report back if you're up to date and still having this happen.

--Adam

**Comment by Martingales** [comment]
Ah yes, this helps. I haven't updated in a few weeks due to the number of samples and the related long run time.

Thank you!
